// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tactdbjrdqhfpozfigrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhY3RkYmpyZHFoZnBvemZpZ3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDAyNTgsImV4cCI6MjA3NDI3NjI1OH0.wesNZIrBibS_N2K3T7vBHyq1nlYJ-ZzY3dqY4vl5O0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});